config/routes.rb
Rails.application.routes.draw do
  get 'admin_dashboard/dashboard', as: :admin_dashboard
  get 'admin_dashboard/select_employee_for_report', as: :select_employee_for_report
  get 'admin_dashboard/multiple_employees_report', as: :multiple_employees_report

  get 'employees_dashboard/dashboard', as: 'employees_dashboard'
  #get 'employee_dashboard/check_in'
  #get 'employee_dashboard/check_out'
  #get 'employee_dashboard/assistance_report'
  #get 'admin_session/dashboard'

  #get 'admin_session/select_employee_for_report'
  #get 'admin_session/multiple_employees_report'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ERB Controllers
  root 'welcome#index'

  resources :employees

  post 'login', to: 'employees_session#create', as: :employees_login
  get 'logout', to: 'employees_session#destroy', as: :employees_logout

  resources :checks, only: [:create]
  #post 'employees_check_in', to: 'employees_dashboard#check_in', as: 'employees_check_in'
  #post 'employees_check_out', to: 'employees_dashboard#check_out', as: 'employees_check_out'

  get 'employees_report', to: 'employees_dashboard#assistance_report'
  post 'employees_report', to: 'employees_dashboard#assistance_report'

  get 'admin/login', to: 'admin_session#new', as: :admin_login_form
  post 'admin/login', to: 'admin_session#create', as: :admin_login
  get 'admin/logout', to: 'admin_session#destroy', as: :admin_logout

  # API Controllers

end

app/models/employee.rb
class Employee < ApplicationRecord
  enum gender: { :male => 0, :female => 1 }

  has_secure_password :pin

  has_many :checks

  validates_presence_of :name, :surname, :gender, :email, :code
  validates_uniqueness_of :email, case_sensitive: false
  validates_uniqueness_of :code, case_sensitive: false

  validates_presence_of :pin, on: :create
  validates :pin, format: {with: /\A\d+\z/, message: "El PIN puede contener solo dígitos" }, allow_blank: true
  #validates_length_of :pin, minimum: 4, maximum: 4
  validates :pin, length: { is: 4 }, allow_blank: true

  scope :by_name, -> (name) { where("name ILIKE ?", "%#{sanitize_sql_like(name)}%") }
  scope :by_surname, -> (surname) { where("surname ILIKE ?", "%#{sanitize_sql_like(surname)}%") }
  scope :by_email, -> (email) { where("email ILIKE ?", "%#{sanitize_sql_like(email)}%") }
  scope :by_gender, -> (gender) { where(gender: gender) }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :admin_authorized
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all

    @search = params[:search]
    if @search.present?
      @name = @search[:name]
      @surname = @search[:surname]
      @email = @search[:email]

      @gender = @search[:gender]&.to_i

      @employees = Employee.by_name(@name).by_surname(@surname).by_email(@email)
      @employees = @employees.by_gender(@gender) if @gender.present?
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)

    check_result_and_redirect('Empleado registrado', new_employee_path)
  end

  def show
    # set_employee
  end

  def edit
    # set_employee
  end

  def update
    params_to_use = employee_params
    if params[:employee][:pin].blank? && params[:employee][:pin_confirmation].blank?
      params[:employee].delete(:pin)
      params[:employee].delete(:pin_confirmation)
      params_to_use = employee_params_whitout_pin
    end

    @employee.update(params_to_use)

    check_result_and_redirect('Empleado actualizado', edit_employee_path)
  end

  def destroy
    @employee.destroy

    flash[:notice] = 'Empleado eliminado'
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(
        :name,
        :surname,
        :gender,
        :email,
        :pin,
        :pin_confirmation,
        :code)
  end

  def employee_params_whitout_pin
    params.require(:employee).permit(
        :name,
        :surname,
        :gender,
        :email,
        :code)
  end

  def set_employee
    begin
      @employee = Employee.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'Empleado no encontrado'
      redirect_to employees_path
    end
  end

  def check_result_and_redirect(success_msg, rollback_url)
    if @employee.valid?
      flash[:notice] = success_msg
      redirect_to employees_path
    else
      flash[:errors] = @employee.errors.full_messages
      redirect_to rollback_url
    end
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee_form.html.erb
<%= form_with model: @employee do |f| %>
  <div class="form-group">
    <%= f.label :code, 'Código único de empleado' %>
    <%= f.text_field :code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :surname, 'Apellidos' %>
    <%= f.text_field :surname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :gender, 'Género' %>
    <%= f.select(:gender, [['Mujer', :female], ['Hombre', :male]]) %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pin, 'PIN' %>
    <%= f.password_field :pin, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pin_confirmation, 'Confirmar PIN' %>
    <%= f.password_field :pin_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Registrar', class: 'btn btn-primary' %>
<% end %>

app/views/employees/edit.html.erb
<div class="ml-auto">
  <%= link_to 'Cancelar', employees_path %>
</div>

<div class="mx-auto mt-5">
  <h1> Modificar datos del Empleado </h1>

  <%= render 'employee_form' %>
</div>

app/views/employees/index.html.erb
<div class="mx-auto mt-5">

  <h1> Índice de empleados </h1>

  <div class="d-flex my-3">
    <div>
      <%= button_to 'Registrar Empleado', new_employee_path, method: :get, class: 'btn btn-primary' %>
    </div>

    <div class="ml-auto">
      <%= button_to 'Panel de Administración', admin_dashboard_path, method: :get, class: 'btn btn-secondary' %>
    </div>
  </div>

  <%= render 'shared/employees_list' %>
</div>

app/views/employees/new.html.erb
<div class="ml-auto">
  <%= link_to 'Cancelar', employees_path %>
</div>

<div class="mx-auto mt-5">
  <h1> Registrar Empleado </h1>

  <%= render 'employee_form' %>
</div>

app/views/employees/show.html.erb
<div class="ml-auto">
  <%= link_to 'Volver al Indice de Empleados', employees_path %>
</div>

<div class="mx-auto mt-5">

  <h2> Empleado: <%= @employee.code %></h2>

  <h3> Nombre: <%= "#{@employee.name} #{@employee.surname}"%> </h3>

  <h3> Género: <%= @employee.gender.to_sym == :male ? 'Hombre' : 'Mujer' %> </h3>

  <h3> Email: <%= @employee.email %> </h3>

  <div class="d-flex justify-content-around">
    <%= button_to 'Modificar datos', edit_employee_path, method: :get, class: 'btn btn-warning'%>
    <%= button_to 'Eliminar empleado', employee_path, method: :delete, class: 'btn btn-danger'%>
  </div>
</div>