config/routes.rb
Rails.application.routes.draw do
  get 'admin_dashboard/dashboard', as: :admin_dashboard
  get 'admin_dashboard/select_employee_for_report', as: :select_employee_for_report
  get 'admin_dashboard/multiple_employees_report', as: :multiple_employees_report

  get 'employees_dashboard/dashboard', as: 'employees_dashboard'
  #get 'employee_dashboard/check_in'
  #get 'employee_dashboard/check_out'
  #get 'employee_dashboard/assistance_report'
  #get 'admin_session/dashboard'

  #get 'admin_session/select_employee_for_report'
  #get 'admin_session/multiple_employees_report'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ERB Controllers
  root 'welcome#index'

  resources :employees

  post 'login', to: 'employees_session#create', as: :employees_login
  get 'logout', to: 'employees_session#destroy', as: :employees_logout

  resources :checks, only: [:create]
  #post 'employees_check_in', to: 'employees_dashboard#check_in', as: 'employees_check_in'
  #post 'employees_check_out', to: 'employees_dashboard#check_out', as: 'employees_check_out'

  get 'employees_report', to: 'employees_dashboard#assistance_report'
  post 'employees_report', to: 'employees_dashboard#assistance_report'

  get 'admin/login', to: 'admin_session#new', as: :admin_login_form
  post 'admin/login', to: 'admin_session#create', as: :admin_login
  get 'admin/logout', to: 'admin_session#destroy', as: :admin_logout

  # API Controllers

end

app/controllers/employees_dashboard_controller.rb
class EmployeesDashboardController < ApplicationController
  before_action :employee_authorized

  def dashboard
    last_check = logged_employee.checks&.last

    @checked_out = last_check.nil? || last_check.check_out?
  end

  def assistance_report
    if params[:date].nil?
      @base_date = Date.today
    else
      @base_date = Date.new.change(month: params[:date][:month].to_i, year: params[:date][:year].to_i)
    end

    start_date = @base_date.beginning_of_month
    end_date = @base_date.end_of_month

    @checks = ChecksController.checks(logged_employee, start_date, end_date)

    separate_in_and_out

    if @check_ins.size - @check_outs.size > 1
      Rails.logger.error "Database is INCONSISTENT. For employee #{logged_employee} the difference " +
                             "between CHECK_INS and CHECK_OUTS is more than 1."
      flash[:error] = 'Hubo un error en la Base de Datos, por favor notifique al personal de tecnología.'
      redirect_to root_path and return
    end

    calculate_hours
  end

  private

  def separate_in_and_out
    @check_ins = []
    @check_outs = []
    @checks.each do |check|
      if check.check_in?
        @check_ins.push(check)
      else
        @check_outs.push(check)
      end
    end
  end

  def calculate_hours
    @total_hours = 0
    @hours = []
    @check_ins.each_with_index do |check_in, i|
      break if @check_outs.size <= i

      diff = TimeDifference.between(@check_outs[i].created_at, check_in.created_at).in_hours
      @total_hours += diff
      @hours.push(diff)
    end
  end
end

app/helpers/employees_dashboard_helper.rb
module EmployeesDashboardHelper
end

app/views/employees_dashboard/assistance_report.html.erb
<div class="mx-auto mt-5">
  <h2> Reporte de asistencia </h2>
</div>

<div class="ml-auto">
  <%= link_to 'Volver', employees_dashboard_path %>
</div>

<div class="mx-auto mt-5">

  <%= form_tag employees_report_path, class: 'form-inline d-flex justify-content-center mb-2' do |f| %>
    <div class="form-group mr-5">
      <label class="mr-2"> Mes: </label>
      <%= select_month(@base_date) %>
    </div>

    <div class="form-group mr-5">
      <label class="mr-2"> Año: </label>
      <%= select_year(@base_date, :start_year => Date.today.year - 10, :end_year => Date.today.year) %>
    </div>

    <%= submit_tag 'Buscar Reporte', class: 'btn btn-primary btn-small' %>
  <% end %>

  <h5> NOTA: No se tiene en cuenta la sesión actual de trabajo que aún no se ha cerrado </h5>

  <h4> Total de horas trabajadas: <%= @total_hours.round(2) %>  </h4>

  <table class="table">
    <thead>
      <tr>
        <th scope="col"> Entrada </th>
        <th scope="col"> Salida </th>
        <th scope="col"> Horas </th>
      </tr>
    </thead>

    <tbody>

    <% @check_outs.each_with_index do | check_out, i | %>

      <tr>
        <th> <%= @check_ins[i].created_at.localtime.to_s(:db) %> </th>
        <th> <%= check_out.created_at.localtime.to_s(:db) %> </th>
        <th> <%= @hours[i].round(2) %> </th>
      </tr>

    <% end %>

    </tbody>
  </table>
</div>

app/views/employees_dashboard/dashboard.html.erb
<div class="ml-auto">
  <%= link_to 'Salir', employees_logout_path %>
</div>

<div class="mx-auto mt-5">
  <%= form_with url: checks_path, method: :post do |f| %>
    <% if @checked_out %>
      <%= f.submit 'Registrar Entrada', class: 'btn btn-success' %>
    <% else %>
      <%= f.submit 'Registrar Salida', class: 'btn btn-danger' %>
    <% end %>
  <% end %>

  <h6 class="mt-5"> <%= link_to 'Reporte de Asistencia', employees_report_path %> </h6>
</div>