config/routes.rb
Rails.application.routes.draw do
  get 'admin_dashboard/dashboard', as: :admin_dashboard
  get 'admin_dashboard/select_employee_for_report', as: :select_employee_for_report
  get 'admin_dashboard/multiple_employees_report', as: :multiple_employees_report

  get 'employees_dashboard/dashboard', as: 'employees_dashboard'
  #get 'employee_dashboard/check_in'
  #get 'employee_dashboard/check_out'
  #get 'employee_dashboard/assistance_report'
  #get 'admin_session/dashboard'

  #get 'admin_session/select_employee_for_report'
  #get 'admin_session/multiple_employees_report'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ERB Controllers
  root 'welcome#index'

  resources :employees

  post 'login', to: 'employees_session#create', as: :employees_login
  get 'logout', to: 'employees_session#destroy', as: :employees_logout

  resources :checks, only: [:create]
  #post 'employees_check_in', to: 'employees_dashboard#check_in', as: 'employees_check_in'
  #post 'employees_check_out', to: 'employees_dashboard#check_out', as: 'employees_check_out'

  get 'employees_report', to: 'employees_dashboard#assistance_report'
  post 'employees_report', to: 'employees_dashboard#assistance_report'

  get 'admin/login', to: 'admin_session#new', as: :admin_login_form
  post 'admin/login', to: 'admin_session#create', as: :admin_login
  get 'admin/logout', to: 'admin_session#destroy', as: :admin_logout

  # API Controllers

end

app/views/shared/_employees_list.html.erb
<%= simple_form_for :search, url: employees_path, method: :get, html: { class: 'form-inline' } do |f| %>
  <%= f.input :name, input_html: {value: '', class: 'form-control mr-2', placeholder: 'Nombre'},
              label: false, required: false %>
  <%= f.input :surname, input_html: {value: '', class: 'form-control mr-2', placeholder: 'Apellidos'},
              label: false, required: false %>
  <%= f.input :email, input_html: {value: '', class: 'form-control mr-2', placeholder: 'Email'},
              label: false, required: false %>

  <%= f.submit 'Buscar', class: 'btn btn-primary' %>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Codigo Empleado</th>
    <th scope="col">Nombre</th>
    <th scope="col">Apellidos</th>
    <th scope="col">Email</th>
    <th scope="col"></th>
  </tr>
  </thead>

  <tbody>
  <% @employees.each do |employee| %>
    <tr>
      <th scope="row"> <%= employee.code %> </th>
      <td> <%= employee.name %> </td>
      <td> <%= employee.surname %> </td>
      <td> <%= employee.email %> </td>
      <td>
        <div class="d-flex">
          <%= button_to 'Ver', employee_path(employee), method: :get, class: 'btn btn-success mr-1' %>
          <%= button_to 'Editar', edit_employee_path(employee), method: :get, class: 'btn btn-warning mr-1' %>
          <%= button_to 'Eliminar', employee_path(employee), method: :delete, class: 'btn btn-danger' %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:warning] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= error %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>